### ISSUE TITLE
beta10 - Spotify.getPlayer() crash on galaxy s6 due to the lack of 64 bit native libraries

### ISSUE THREAD

**Issue by acidmath** [spotify/android-sdk#122]
I loaded up my app on a galaxy s6 and it crashes when i play a track. I am able to authorize a user and browse tracks, so it seems like it is the player aar file that is at fault. 

here is the printout

```
05-19 19:42:49.394  15934-15934/my.app.package E/ViewRootImpl﹕ sendUserActionEvent() mView == null
05-19 19:42:49.394  15934-15934/my.app.package E/MediaPlayerActivity﹕ about to load spotify image: https://i.scdn.co/image/68fdf05b02435e4c11667a2749c609e46693107b
05-19 19:42:49.394  15934-15934/my.app.package E/MediaPlayerActivity﹕ post execute play task - can skip: false
05-19 19:42:49.394  15934-15934/my.app.package E/MediaPlayerActivity﹕ setting track duration: 203413
05-19 19:42:49.394    3536-4702/? D/ActivityManager﹕ retrieveServiceLocked(): component = com.google.android.gms/com.google.android.location.network.NetworkLocationService; callingUser = 0; userId(target) = 0
05-19 19:42:49.394    4954-4954/? I/LoadedApk﹕ getClassLoader :dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-1/lib/arm64, /vendor/lib64, /system/lib64]]]
05-19 19:42:49.394    3022-3358/? D/AudioPolicyManager﹕ getDeviceForStrategy mLastPolicySelection device = 0
05-19 19:42:49.394    3022-3358/? D/AudioPolicyManager﹕ getDeviceForStrategy mLastPolicySelection device = 0
05-19 19:42:49.404    3536-3536/? E/LocSvc_flp﹕ I/===> int flp_inject_location(FlpLocation*) line 222
05-19 19:42:49.404  15934-15934/my.app.package D/AndroidRuntime﹕ Shutting down VM
05-19 19:42:49.414  15934-15934/my.app.package E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: my.app.package, PID: 15934
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/my.app.package-1/base.apk"],nativeLibraryDirectories=[/data/app/my.app.package-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.spotify.sdk.android.player.NativeSdkPlayer.nativeInit(NativeSdkPlayer.java:44)
            at com.spotify.sdk.android.player.NativeSdkPlayer.<clinit>(NativeSdkPlayer.java:34)
            at com.spotify.sdk.android.player.Player.<init>(Player.java:310)
            at com.spotify.sdk.android.player.Player.create(Player.java:356)
            at com.spotify.sdk.android.player.Player.access$000(Player.java:86)
            at com.spotify.sdk.android.player.Player$Builder.build(Player.java:282)
            at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:110)
            at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:76)
            at my.app.package.activities.MediaPlayerActivity.initSpotifyPlayer(MediaPlayerActivity.java:449)
            at my.app.package.activities.MediaPlayerActivity.access$700(MediaPlayerActivity.java:89)
            at my.app.package.activities.MediaPlayerActivity$22.onPostExecute(MediaPlayerActivity.java:1416)
            at my.app.package.activities.MediaPlayerActivity$22.onPostExecute(MediaPlayerActivity.java:1027)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
05-19 19:42:49.414    3536-3777/? D/EnterpriseDeviceManagerService﹕ isManagedProfileUser(): userId = 0
05-19 19:42:49.414    3536-3777/? D/EnterpriseDeviceManagerService﹕ is permission granted: false
05-19 19:42:49.434    3536-3777/? W/ActivityManager﹕ Force finishing activity my.app.package/.activities.MediaPlayerActivity
```

**Comment by kaaes** [comment]
It is looking for the native libraries in the arm64 folder inside the aar, it doesn't find it and it crashes. This SDK doesn't have a support for 64 bit architecture yet.
Until we add this - it should be possible to run armv7 libraries on armv8 device (S6) but you might need to check other dependencies of your app and possibly modify build files to not use 64 bit native libs.

**Comment by acidmath** [comment]
since android studio generates it's own android.mk file, it was tricky to find info for awhile, but this stackoverflow post resolved my issue

http://stackoverflow.com/questions/30761725/android-ndk-multlib-support-using-gradle

**Comment by kocyigityunus** [comment]
for who ever facing this issue. first unzip the players .aar file.
inside that unzipped .aar file there will ve a folder called jni. inside that jni folder the .so files will be in different folders for different architectures (armeabi, x86,armeabi-v7a )

create a new folder inside your app next to "libs" folder. call it "jni". copy that "armeabi", "x86", "armeabi-v7a" folders inside the "jni folder." 

then paste this config next to "android.defaultConfig" or "android.buildTypes" or "android.signingConfigs" in to the your app's build.gradle file ( "build.gradle(app)" ). 

```
sourceSets.main {
        jniLibs.srcDirs = ['jni'] // copy folder that includes *.so to package
    }
```

if you are not sure where to paste it. just search in the google.

the final project structure will be like this : 

![screen shot 2016-04-08 at 10 17 37](https://cloud.githubusercontent.com/assets/922418/14376602/2b23db50-fd73-11e5-9ac6-46065895f0e6.png)

only this way your apk will contain .so files for every architecture. if you have any questions please feel free to ask.

**Comment by LeoKaliazine-Digiflare** [comment]
@kocyigityunus experiencing this kind of crash also on a Samsung S6 device. Except all I get in the logs is: `java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file...` with a list of all the dex files etc...
This happens with beta13 build. I tried your solution with no positive results, also armeabi library is no longer included in the aar.

**Comment by d-kunin** [comment]
We are looking into implementing 64bit support. For now you need to limit the support to 32bit. check #250
