### ISSUE TITLE
BUG: Player.seekToPosition(0) then Player.pause(); and Player.resume();

### ISSUE THREAD

**Issue by bamsbamx** [spotify/android-sdk#146]
It seems that restarting a track following the next way causes a playback error:

```java
for (int i = 0; i<n; i++)
    Player.queue();    //Queue some tracks

//TRACK_CHANGED and PLAY received. Starts playing
//After few seconds:
Player.seekToPosition(0);
Player.pause();

//Then, try to resume
Player.resume();
```

Doing this, it wont start the track over, it doesnt play. In addition, it calls onPlayBackError() with ErrorType.ERROR_PLAYBACK.

However, when trying to Player.Pause() AGAIN it throws the following logcat:
```
08-22 13:33:39.348  28978-29522/com.anrapps.spotify E/SpotifySDK﹕ Throwing exception, failed SpPlaybackSeek with error code 1 (The operation failed due to an unspecified issue)
08-22 13:33:39.348  28978-29522/com.anrapps.spotify W/System.err﹕ com.spotify.sdk.android.player.NativeSpotifyException: Failed SpPlaybackSeek with error code 1 (The operation failed due to an unspecified issue)
08-22 13:33:39.348  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.NativeSdkPlayer.nativeSeekToPosition(Native Method)
08-22 13:33:39.348  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.NativeSdkPlayer.seekToPosition(NativeSdkPlayer.java:209)
08-22 13:33:39.356  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.Player$22.call(Player.java:995)
08-22 13:33:39.356  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.Player$22.call(Player.java:992)
08-22 13:33:39.356  28978-29522/com.anrapps.spotify W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-22 13:33:39.356  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.Player.startRunLoop(Player.java:477)
08-22 13:33:39.356  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.Player.access$100(Player.java:86)
08-22 13:33:39.356  28978-29522/com.anrapps.spotify W/System.err﹕ at com.spotify.sdk.android.player.Player$1.run(Player.java:367)
```

After all this, if I call Player.resume() again, it finally starts playing.

In short: Calling seekToPosition(0) and then pause seems to break the playback. However if we resume, pause and resume again the player, it starts playing again

THERE SHOULD BE A Player.stop() METHOD WHICH ALLOWS TO PAUSE THE TRACK IN POSITION 0;

Please fix this as soon as possible

**Comment by d-kunin** [comment]
Please check it in beta 21.

THERE WILL BE NO Player.stop() METHOD WHICH ALLOWS TO PAUSE THE TRACK IN POSITION 0;
;)
