### ISSUE TITLE
need error handling for unitialized audio track

### ISSUE THREAD

**Issue by troymolnar** [spotify/android-sdk#160]
if android has too many audio players active (around 32 is the limit), and spotify attempts to play a song, it will crash:

null
java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
at android.media.AudioTrack.play(AudioTrack.java:1574)
at com.spotify.sdk.android.player.AudioTrackController.createAudioTrack(AudioTrackController.java:217)
at com.spotify.sdk.android.player.AudioTrackController.onAudioDataDelivered(AudioTrackController.java:124)
at com.spotify.sdk.android.player.Player.onAudioDelivered(Player.java:1189)
at com.spotify.sdk.android.player.NativeSdkPlayer.onAudioDelivered(NativeSdkPlayer.java:273)
at com.spotify.sdk.android.player.NativeSdkPlayer.nativePumpEvents(Native Method)
at com.spotify.sdk.android.player.NativeSdkPlayer.pumpEvents(NativeSdkPlayer.java:74)
at com.spotify.sdk.android.player.Player.startRunLoop(Player.java:484)
at com.spotify.sdk.android.player.Player.access$100(Player.java:86)
at com.spotify.sdk.android.player.Player$1.run(Player.java:367)

Getting to this state is due to an issue like this:
http://stackoverflow.com/questions/11964623/audioflinger-could-not-create-track-status-12/12024769#12024769

**Comment by kaaes** [comment]
Thanks for the report! We'll have a look at this issue.

**Comment by kaaes** [comment]
We added the error handling in beta12. Please let us know if this happens again
