### ISSUE TITLE
Crash in LoginDialog

### ISSUE THREAD

**Issue by RomainPiel** [spotify/android-sdk#164]
I'm not sure how to reproduce this but i'm receiving crashes from the Spotify sdk:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.spotify.sdk.android.authentication.LoginActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:119)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4873)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:528)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.spotify.sdk.android.authentication.LoginDialog.<init>(LoginDialog.java:86)
       at com.spotify.sdk.android.authentication.AuthenticationClient.showLoginDialog(AuthenticationClient.java:393)
       at com.spotify.sdk.android.authentication.AuthenticationClient.authenticate(AuthenticationClient.java:356)
       at com.spotify.sdk.android.authentication.LoginActivity.onCreate(LoginActivity.java:53)
       at android.app.Activity.performCreate(Activity.java:5218)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2038)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:119)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4873)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:528)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
It happens on 4.1.1 and 5.0.2. I also noted that all devices are routed and it seems it was triggered by some sort of monkey runner.

**Comment by kaaes** [comment]
Thank you for the report. We'll look into this issue.

**Comment by kaaes** [comment]
This should be now fixed. Please let us know if it happens again

**Comment by RomainPiel** [comment]
Cool, will do! Thanks
