### ISSUE TITLE
Error getPlaylistTracks Spotify

### ISSUE THREAD

**Issue by zvalejandro** [spotify/android-sdk#215]
Request:
`spotifyService.getPlaylistTracks(spotifyCredentials.getUserSpotify(), idPlaylist, options);`

Output
```
                                                                         Process: com.ironbit.urband.test1, PID: 31981
                                                                          retrofit.RetrofitError
                                                                              at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
                                                                              at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                                              at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                              at $Proxy1.getPlaylistTracks(Unknown Source)
                                                                              at com.ironbit.urband.test1.view.utils.SpotifyCallbackUtils.getListSongs(SpotifyCallbackUtils.java:83)
                                                                              at com.ironbit.urband.test1.presenter.services.MediaPlayerService.getListSongsSpotify(MediaPlayerService.java:539)
                                                                              at com.ironbit.urband.test1.presenter.fragments.HomeMusicSpotifySongs.onCreateView(HomeMusicSpotifySongs.java:47)
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:145)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                           Caused by: android.os.NetworkOnMainThreadException
                                                                              at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                                                                              at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:778)
                                                                              at com.android.okio.Okio$1.write(Okio.java:73)
                                                                              at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:154)
                                                                              at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:130)
                                                                              at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:80)
                                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:793)
                                                                              at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
                                                                              at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                              at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
                                                                              at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                              at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
                                                                              at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
                                                                              at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
                                                                              at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                                                                              at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) 
                                                                              at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
                                                                              at $Proxy1.getPlaylistTracks(Unknown Source) 
                                                                              at com.ironbit.urband.test1.view.utils.SpotifyCallbackUtils.getListSongs(SpotifyCallbackUtils.java:83) 
                                                                              at com.ironbit.urband.test1.presenter.services.MediaPlayerService.getListSongsSpotify(MediaPlayerService.java:539) 
                                                                              at com.ironbit.urband.test1.presenter.fragments.HomeMusicSpotifySongs.onCreateView(HomeMusicSpotifySongs.java:47) 
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248) 
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) 
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613) 
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517) 
                                                                              at android.os.Handler.handleCallback(Handler.java:739) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:145) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                              at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by zvalejandro** [comment]
Bug fixes when:

```
if (android.os.Build.VERSION.SDK_INT > 9) {
            StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
            StrictMode.setThreadPolicy(policy);
            Pager<PlaylistTrack > response = spotifyService.getPlaylistTracks(spotifyCredentials.getUserSpotify(), idPlaylist, options);
            Log.d("spotify", " response total: " + response.total);
        }
```

**Comment by AppsAndreevich** [comment]
@zvalejandro Ohhh man!! You are the best! It worked perfectly and fixed my problem!!! I was trying for a lot of time! Thanks, thanks!!!!!!
