### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/android-sdk#217]
I know this was closed (# 174), but you failed to answer when the fix is being released.
This is happening in the Beta 12.

Class not found when unmarshalling: com.spotify.sdk.android.authentication.AuthenticationRequest
                                        java.lang.ClassNotFoundException: com.spotify.sdk.android.authentication.AuthenticationRequest
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.Class.forName(Class.java:308)
                                            at java.lang.Class.forName(Class.java:272)
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
                                            at android.os.Parcel.readParcelable(Parcel.java:2239)
                                            at android.os.Parcel.readValue(Parcel.java:2146)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                            at android.os.BaseBundle.getString(BaseBundle.java:918)
                                            at android.content.Intent.getStringExtra(Intent.java:5434)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1871)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1409)
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5105)
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4890)
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:144)
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3279)
                                            at android.os.Binder.execTransact(Binder.java:446)
                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.spotify.sdk.android.authentication.AuthenticationRequest" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                            at java.lang.Class.classForName(Native Method) 
                                            at java.lang.Class.forName(Class.java:308) 
                                            at java.lang.Class.forName(Class.java:272) 
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2275) 
                                            at android.os.Parcel.readParcelable(Parcel.java:2239) 
                                            at android.os.Parcel.readValue(Parcel.java:2146) 
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479) 
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                            at android.os.BaseBundle.getString(BaseBundle.java:918) 
                                            at android.content.Intent.getStringExtra(Intent.java:5434) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1871) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1409) 
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5105) 
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4890) 
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:144) 
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3279) 
                                            at android.os.Binder.execTransact(Binder.java:446) 
                                        	Suppressed: java.lang.ClassNotFoundException: com.spotify.sdk.android.authentication.AuthenticationRequest
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                            		... 18 more
                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by sampurcell93** [comment]
Hey Brad, have you had any luck figuring this out? I am running into the exact same problem on a Galaxy S6 and it's really throwing a wrench into the situation.

**Comment by sampurcell93** [comment]
Additionally, this error only occurs in a signed apk distributed through the Play Store. I am developing in React Native, and when in dev mode from the phone, auth works perfectly

**Comment by sampurcell93** [comment]
It appears that this was a proguard problem in my case. Adding 
`-keep class com.spotify.sdk.android.authentication.AuthenticationRequest` to my proguard rules did the trick. Hope it helps you @Brad-Jackson.

**Comment by Brad-Jackson** [comment]
I'm not currently using pro guard. Thanks for the thoughts.

**Comment by d-kunin** [comment]
That was addressed in the latest release, please verify https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13
