### ISSUE TITLE
Exception: Unable to destroy activity {xxx/com.spotify.sdk.android.authentication.LoginActivity} - NullPointerException

### ISSUE THREAD

**Issue by kenumir** [spotify/android-sdk#219]
Stack trace 
```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {xxx/com.spotify.sdk.android.authentication.LoginActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3486)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3504)
       at android.app.ActivityThread.access$1400(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5024)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.spotify.sdk.android.authentication.LoginActivity.onDestroy(LoginActivity.java:101)
       at android.app.Activity.performDestroy(Activity.java:5403)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3473)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3504)
       at android.app.ActivityThread.access$1400(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5024)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by d-kunin** [comment]
@kenumir we need steps and context of the issue. Please verify that it still happens in beta 21 and feel free to reopen in case it is still relevant providing more details.
