### ISSUE TITLE
Spotify AuthHandler crashes on creating AuthenticationClient on Android 4.4

### ISSUE THREAD

**Issue by shovelend** [spotify/android-sdk#231]
Hello guys,
I just published my app to play, and i noticed some crashes. On Android 4.4 devices when i try to open the authentication client i get the stacktrace:

java.lang.NoClassDefFoundError: com.spotify.sdk.android.authentication.SpotifyAuthHandler
                                                                    at com.spotify.sdk.android.authentication.AuthenticationClient.<init>(AuthenticationClient.java:336)
                                                                    at com.spotify.sdk.android.authentication.LoginActivity.onCreate(LoginActivity.java:78)
                                                                    at android.app.Activity.performCreate(Activity.java:5231)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                    at dalvik.system.NativeStart.main(Native Method)

On Android 5+ devices it's working fine. I've tried to modify the proguard file, didn't do a thing.

Thanks in advance, and keep up the good work!

**Comment by d-kunin** [comment]
Can you check how does it work with the latest release https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13 ?

**Comment by shovelend** [comment]
Hello, 
I've managed to fix this issue by extending MultiDexApplication for my application class.
