### ISSUE TITLE
UnsatisfiedLinkError : couldn't find "libgnustl_shared.so"

### ISSUE THREAD

**Issue by alexandre-lefranc-ezeeworld** [spotify/android-sdk#251]
Hi,

My application crashes after calling `Spotify.getPlayer()` on a Galaxy S7.
I use the latest version of the SDK : 1.0.0-beta13

`                                                                         java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp.android-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.android-2/lib/arm64, /data/app/com.myapp.android-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                             at java.lang.System.loadLibrary(System.java:1076)
                                                                             at com.spotify.sdk.android.player.NativeSdkPlayer.nativeInit(NativeSdkPlayer.java:44)
                                                                             at com.spotify.sdk.android.player.NativeSdkPlayer.<clinit>(NativeSdkPlayer.java:34)
                                                                             at com.spotify.sdk.android.player.Player.<init>(Player.java:310)
                                                                             at com.spotify.sdk.android.player.Player.create(Player.java:356)
                                                                             at com.spotify.sdk.android.player.Player.access$000(Player.java:86)
                                                                             at com.spotify.sdk.android.player.Player$Builder.build(Player.java:282)
                                                                             at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:110)
                                                                             at com.spotify.sdk.android.player.Spotify.getPlayer(Spotify.java:76)
                                                                             at com.wallofmusic.android.players.SpotifyPlayer.createPlayer(SpotifyPlayer.java:102)`

**Comment by ZinoKader** [comment]
I've found this can come down to libraries doing funky stuff. I've isolated the issue (for me) down to the library https://github.com/miguelbcr/RxPaparazzo. Even without initializing it anywhere, it does something that provokes this error for me. If this recently happened, check your commits and see if you added any libraries at the time the issue started showing up.

**Comment by d-kunin** [comment]
As they have mentioned, you will need to disable support of 64bit architecture. Currently Spotify SDK does not support 64bit, but we are looking into it.

**Comment by k-misztal** [comment]
Is there any info about that error? When we can expect SpotifySDK to support 64bit?

**Comment by erdtman** [comment]
64 bit support is included in latest release
