### ISSUE TITLE
ActivityNotFound exception from LoginDialog

### ISSUE THREAD

**Issue by velleic** [spotify/android-sdk#257]
Received this error report recently:

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.spotify.com/au/signup/?forward_url=https://accounts.spotify.com/en/authorize?client_id=<client id here>&response_type=token&redirect_uri=<redirect uri here>&scope=user-read-private%20streaming }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
       at android.app.Activity.startActivityForResult(Activity.java:3449)
       at android.app.Activity.startActivityForResult(Activity.java:3388)
       at android.app.Activity.startActivity(Activity.java:3646)
       at android.app.Activity.startActivity(Activity.java:3614)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:290)
       at com.spotify.sdk.android.authentication.LoginDialog$2.shouldOverrideUrlLoading(LoginDialog.java:165)
       at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:268)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:396)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5473)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:854)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

This version uses beta12. The only other info I have is that the android version is 4.3. Seems the user may not have a web browser or something?

**Comment by d-kunin** [comment]
Well, I think you are right @velleic, there is nothing that supports web uris installed on the device. 
There is not much we can do about it.
