### ISSUE TITLE
beta21: Failed SpPlayUri with error code 1

### ISSUE THREAD

**Issue by Uni2K** [spotify/android-sdk#275]
Hey,
did everything like in the documentation:
https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/
Everything works except starting the playback.
Player is initialized and the user is logged in.

But when I call: 
`mPlayer.play("spotify:track:25GC50HslaaruyrKjdu0lP",0,2);`
It gives the following error:

>  com.spotify.sdk.android.player.NativeSpotifyException: Failed SpPlayUri with error code 1 (The operation failed due to an unspecified issue)
at com.spotify.sdk.android.player.SpotifyPlayer.nativePlayUri(Native Method)
at com.spotify.sdk.android.player.SpotifyPlayer.access$900(SpotifyPlayer.java:81)
at com.spotify.sdk.android.player.SpotifyPlayer$12.run(SpotifyPlayer.java:710)
at com.spotify.sdk.android.player.SpotifyPlayer.startRunLoop(SpotifyPlayer.java:431)
at com.spotify.sdk.android.player.SpotifyPlayer.access$100(SpotifyPlayer.java:81)
at com.spotify.sdk.android.player.SpotifyPlayer$1.run(SpotifyPlayer.java:350)

I looked up the lines but  couldnt find anything helpfull.
The error doesnt depend on the URIs. (I tried several)

Any help or advices are very appreciated.
Thank you.

**Comment by Dmitry-Scherbakov** [comment]
I have the same issue. Did you resolve it?

**Comment by Uni2K** [comment]
Hey,

i stopped using the API, because i guess that this errorcode appears when
you try to play a song and you dont have a premium account.
Read the readme again, there is written: "You can only play songs with this
API when you are a premium member" (or something like that).

Greetings.

2016-09-21 15:11 GMT+02:00 Dmitry-Scherbakov <notifications@github.com>:
