### ISSUE TITLE
Crashes when starting music playback

### ISSUE THREAD

**Issue by johra** [spotify/android-sdk#318]
## Description
Crashes when starting music playback.

### Versions
Android SDK version: 24

### Severity
Catastrophic

## Steps to Reproduce
1. Add SDK to react-native template
2. Start music playback

### Actual behaviour
App crashes

### Expected behaviour
Music should start playing

## Logs
12-07 03:35:55.386 11324-13181/com.myapp E/AudioTrack: Unable to query output sample rate for stream type -1; status -1
12-07 03:35:55.386 11324-13181/com.myapp E/AudioTrack-JNI: AudioTrack::getMinFrameCount() for sample rate 44100 failed with status -1
12-07 03:35:55.386 11324-13181/com.myapp E/android.media.AudioTrack: getMinBufferSize(): error querying hardware
12-07 03:35:55.388 11324-13181/com.myapp E/AndroidRuntime: FATAL EXCEPTION: SpotifyPlayerThreadcom.spotify.sdk.android.player.SpotifyPlayer@6b63d0d
                                                             Process: com.myapp, PID: 11324
                                                             java.lang.IllegalArgumentException: Invalid audio buffer size.
                                                                 at android.media.AudioTrack.audioBuffSizeCheck(AudioTrack.java:871)
                                                                 at android.media.AudioTrack.<init>(AudioTrack.java:493)
                                                                 at android.media.AudioTrack.<init>(AudioTrack.java:413)
                                                                 at android.media.AudioTrack.<init>(AudioTrack.java:370)
                                                                 at com.spotify.sdk.android.player.AudioTrackController.createAudioTrack(AudioTrackController.java:207)
                                                                 at com.spotify.sdk.android.player.AudioTrackController.onAudioDataDelivered(AudioTrackController.java:123)
                                                                 at com.spotify.sdk.android.player.SpotifyPlayer.onAudioDelivered(SpotifyPlayer.java:919)
                                                                 at com.spotify.sdk.android.player.SpotifyPlayer.nativePumpEvents(Native Method)
                                                                 at com.spotify.sdk.android.player.SpotifyPlayer.startRunLoop(SpotifyPlayer.java:410)
                                                                 at com.spotify.sdk.android.player.SpotifyPlayer.access$100(SpotifyPlayer.java:79)
                                                                 at com.spotify.sdk.android.player.SpotifyPlayer$1.run(SpotifyPlayer.java:331)
12-07 03:35:56.000 11324-11344/com.myapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0xee9725b0

**Comment by pedro-otero** [comment]
Exact same log output and behavior here

**Comment by martinvano** [comment]
I have something similar on API 24 and 25. The stacktrace goes like this:
`com.spotify.sdk.android.player.AudioTrackController.createAudioTrack (AudioTrackController.java:190)
com.spotify.sdk.android.player.AudioTrackController.onAudioDataDelivered (AudioTrackController.java:123)
com.spotify.sdk.android.player.SpotifyPlayer.onAudioDelivered (SpotifyPlayer.java:919)
com.spotify.sdk.android.player.SpotifyPlayer.nativePumpEvents (SpotifyPlayer.java)
com.spotify.sdk.android.player.SpotifyPlayer.startRunLoop (SpotifyPlayer.java:410)
com.spotify.sdk.android.player.SpotifyPlayer.access$100 (SpotifyPlayer.java:79)
com.spotify.sdk.android.player.SpotifyPlayer$1.run (SpotifyPlayer.java:331)`

but the error says `Exception java.lang.IllegalStateException: Input source has 0 channels`

**Comment by AbdulSamadQureshi** [comment]
Any solution to this problem? i too started experiencing without any change in my code.
