### ISSUE TITLE
Input source has 0 channels

### ISSUE THREAD

**Issue by Meisolsson** [spotify/android-sdk#330]
## Description
The SDK gives 0 channels in the AudioController.onAudioDataDelivered sometimes. I has not happened to me personally but I have user whom had the bug.

### Versions
Spotify SDK: player-24-noconnect-2.20b
Android OS: 6.0, 6.0.1, 5.1.1

### Severity
Minor

## Logs
The part of the logs which are handeld by the lib from Bugsnag
```
at com.spotify.sdk.android.player.SpotifyPlayer.onAudioDelivered(SpotifyPlayer.java:919)
at com.spotify.sdk.android.player.SpotifyPlayer.nativePumpEvents(SpotifyPlayer.java:-2)
at com.spotify.sdk.android.player.SpotifyPlayer.startRunLoop(SpotifyPlayer.java:410)
at com.spotify.sdk.android.player.SpotifyPlayer.access$100(SpotifyPlayer.java:79)
at com.spotify.sdk.android.player.SpotifyPlayer$1.run(SpotifyPlayer.java:331)
```

**Comment by xiaoming-vinci** [comment]
I have the same problem.

`06-01 18:06:12.315 E/AndroidRuntime: FATAL EXCEPTION: SpotifyPlayerThreadcom.spotify.sdk.android.player.SpotifyPlayer@449bcae8
                                     Process: im.vinci.headphone, PID: 901
                                     java.lang.IllegalStateException: Input source has 0 channels
                                         at com.spotify.sdk.android.player.AudioTrackController.createAudioTrack(AudioTrackController.java:190)
                                         at com.spotify.sdk.android.player.AudioTrackController.onAudioDataDelivered(AudioTrackController.java:123)
                                         at com.spotify.sdk.android.player.SpotifyPlayer.onAudioDelivered(SpotifyPlayer.java:919)
                                         at com.spotify.sdk.android.player.SpotifyPlayer.nativePumpEvents(Native Method)
                                         at com.spotify.sdk.android.player.SpotifyPlayer.startRunLoop(SpotifyPlayer.java:410)
                                         at com.spotify.sdk.android.player.SpotifyPlayer.access$100(SpotifyPlayer.java:79)
                                         at com.spotify.sdk.android.player.SpotifyPlayer$1.run(SpotifyPlayer.java:331)`

**Comment by eddiecrawford** [comment]
Same strack trace. Even using own Implemented Audio Controkker:
`2017-09-13 14:40:07,887 - INFO -KEY_EVENTS - [+20] handleNewClientConnection: clientId=Ke Qingqing(cindy)
2017-09-13 14:41:14,420 - ERROR -KEY_EVENTS - [+20] app.crash, thread_name=SpotifyPlayerThreadcom.spotify.sdk.android.player.SpotifyPlayer@c605aa2, 
java.lang.IllegalStateException: Input source has 0 channels
at com.ubnt.frl.app.ui.flow.spotify.FrAudioController.createAudioTrack(FrAudioController.java:116)
at com.ubnt.frl.app.ui.flow.spotify.FrAudioController.onAudioDataDelivered(FrAudioController.java:60)
at com.spotify.sdk.android.player.SpotifyPlayer.onAudioDelivered(SpotifyPlayer.java:919)
at com.spotify.sdk.android.player.SpotifyPlayer.nativePumpEvents(Native Method)
at com.spotify.sdk.android.player.SpotifyPlayer.startRunLoop(SpotifyPlayer.java:410)
at com.spotify.sdk.android.player.SpotifyPlayer.access$100(SpotifyPlayer.java:79)
at com.spotify.sdk.android.player.SpotifyPlayer$1.run(SpotifyPlayer.java:331)`

**Comment by mingxin-yang** [comment]
I have the same problem,do you solve it ?
