### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;

### ISSUE THREAD

**Issue by andras-gyarmati** [spotify/android-sdk#347]
## Description
JaCoCo class can not be found

### Versions
Android SDK version: 7.1.1
Spotify app version: 8.0.0.805 armV7
Android OS version: 7.1.1

### Severity
Major

## Steps to Reproduce
1. Follow the toturial to make the app
2. Try to run it

### Actual behaviour
Spotify Android SDK Tutorial app quit with an error on startup

### Expected behaviour
Spotify Android SDK Tutorial app runs without any error

## Logs
04-06 16:34:38.016 3703-3703/? I/art: Late-enabling -Xcheck:jni
04-06 16:34:38.085 3703-3703/? W/ActivityThread: Application com.briantheastronaut.spotifyconnect is waiting for the debugger on port 8100...
04-06 16:34:38.087 3703-3703/? I/System.out: Sending WAIT chunk
04-06 16:34:39.078 3703-3713/com.briantheastronaut.spotifyconnect I/art: Debugger is active
04-06 16:34:39.089 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: Debugger has connected
04-06 16:34:39.089 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:39.290 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:39.491 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:39.691 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:39.892 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:40.093 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:40.293 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 16:34:40.495 3703-3703/com.briantheastronaut.spotifyconnect I/System.out: debugger has settled (1320)
04-06 16:34:40.726 3703-3703/com.briantheastronaut.spotifyconnect I/InstantRun: starting instant run server: is main process
04-06 16:34:40.728 3703-3703/com.briantheastronaut.spotifyconnect V/InstantRun: Starting server socket listening for package com.briantheastronaut.spotifyconnect on android.net.LocalSocketAddress@a64df84
04-06 16:34:40.729 3703-3703/com.briantheastronaut.spotifyconnect V/InstantRun: Started server for package com.briantheastronaut.spotifyconnect
04-06 16:34:40.850 3703-3703/com.briantheastronaut.spotifyconnect D/AndroidRuntime: Shutting down VM
04-06 16:34:40.866 3703-3703/com.briantheastronaut.spotifyconnect E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.briantheastronaut.spotifyconnect, PID: 3703
                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
                                                                                        at com.spotify.sdk.android.authentication.AuthenticationResponse$Type.$jacocoInit(AuthenticationResponse.java)
                                                                                        at com.spotify.sdk.android.authentication.AuthenticationResponse$Type.<clinit>(AuthenticationResponse.java)
                                                                                        at com.briantheastronaut.spotifyconnect.MainActivity.onCreate(MainActivity.java:31)
                                                                                        at android.app.Activity.performCreate(Activity.java:6679)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline" on path: DexPathList[[zip file "/data/app/com.briantheastronaut.spotifyconnect-2/base.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.briantheastronaut.spotifyconnect-2/lib/arm, /data/app/com.briantheastronaut.spotifyconnect-2/base.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.briantheastronaut.spotifyconnect-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                        at com.spotify.sdk.android.authentication.AuthenticationResponse$Type.$jacocoInit(AuthenticationResponse.java) 
                                                                                        at com.spotify.sdk.android.authentication.AuthenticationResponse$Type.<clinit>(AuthenticationResponse.java) 
                                                                                        at com.briantheastronaut.spotifyconnect.MainActivity.onCreate(MainActivity.java:31) 
                                                                                        at android.app.Activity.performCreate(Activity.java:6679) 
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
04-06 16:34:40.884 3703-3703/com.briantheastronaut.spotifyconnect I/Process: Sending signal. PID: 3703 SIG: 9

**Comment by andras-gyarmati** [comment]
workaround with updating app/build.gradle, but they say you cant upload to google play with this method.
buildTypes {
        debug { //added this
            testCoverageEnabled true //added this
        } //added this
        release {
            testCoverageEnabled true //added this
            minifyEnabled false //autogenerated, may differ from yours
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' //autogenerated, may differ from yours
        }
    }
 https://code.google.com/p/android/issues/detail?id=205419

**Comment by andras-gyarmati** [comment]
also needed to disable instant run to be able to run the app here is the log:
##Log
04-06 17:13:29.786 10990-10990/? I/art: Late-enabling -Xcheck:jni
04-06 17:13:29.812 10990-10997/? I/art: Debugger is no longer active
04-06 17:13:29.812 10990-10997/? I/art: Waiting for a blocking GC Instrumentation
04-06 17:13:29.830 10990-10997/? I/art: WaitForGcToComplete blocked for 17.609ms for cause Instrumentation
04-06 17:13:29.830 10990-10990/? W/ActivityThread: Application com.briantheastronaut.spotifyconnect is waiting for the debugger on port 8100...
04-06 17:13:29.830 10990-10997/? I/art: Starting a blocking GC Instrumentation
04-06 17:13:29.831 10990-10990/? I/System.out: Sending WAIT chunk
04-06 17:13:31.840 10990-10997/com.briantheastronaut.spotifyconnect I/art: Debugger is active
04-06 17:13:32.034 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: Debugger has connected
04-06 17:13:32.035 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 17:13:32.235 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 17:13:32.436 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 17:13:32.637 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 17:13:32.838 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 17:13:33.038 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: waiting for debugger to settle...
04-06 17:13:33.239 10990-10990/com.briantheastronaut.spotifyconnect I/System.out: debugger has settled (1306)
04-06 17:13:33.314 10990-10990/com.briantheastronaut.spotifyconnect W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
04-06 17:13:33.315 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at java.io.FileOutputStream.open(Native Method)
04-06 17:13:33.316 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
04-06 17:13:33.316 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.output.FileOutput.openFile(FileOutput.java:67)
04-06 17:13:33.317 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.output.FileOutput.startup(FileOutput.java:49)
04-06 17:13:33.317 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Agent.startup(Agent.java:122)
04-06 17:13:33.317 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Agent.getInstance(Agent.java:50)
04-06 17:13:33.318 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Offline.<clinit>(Offline.java:31)
04-06 17:13:33.319 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Offline.getProbes(Offline.java:51)
04-06 17:13:33.319 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at com.briantheastronaut.spotifyconnect.MainActivity.$jacocoInit(MainActivity.java)
04-06 17:13:33.319 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at com.briantheastronaut.spotifyconnect.MainActivity.<init>(MainActivity.java)
04-06 17:13:33.319 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at java.lang.Class.newInstance(Native Method)
04-06 17:13:33.320 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
04-06 17:13:33.320 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
04-06 17:13:33.320 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
04-06 17:13:33.320 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-06 17:13:33.321 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
04-06 17:13:33.321 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-06 17:13:33.321 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-06 17:13:33.321 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6126)
04-06 17:13:33.322 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-06 17:13:33.322 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-06 17:13:33.322 10990-10990/com.briantheastronaut.spotifyconnect W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-06 17:13:33.486 10990-11058/com.briantheastronaut.spotifyconnect I/Adreno: QUALCOMM build                   : 166ada0, Ifd751822f5
                                                                              Build Date                       : 01/26/16
                                                                              OpenGL ES Shader Compiler Version: XE031.06.00.05
                                                                              Local Branch                     : AU12_SBA
                                                                              Remote Branch                    : 
                                                                              Remote Branch                    : 
                                                                              Reconstruct Branch               : 
04-06 17:13:33.500 10990-11058/com.briantheastronaut.spotifyconnect I/OpenGLRenderer: Initialized EGL, version 1.4
04-06 17:13:33.501 10990-11058/com.briantheastronaut.spotifyconnect D/OpenGLRenderer: Swap behavior 1
04-06 17:13:33.534 10990-10990/com.briantheastronaut.spotifyconnect D/com.spotify.sdk.android.authentication.LoginActivity: https://accounts.spotify.com/authorize?client_id=196ac28788c64ba6a03fa5b94f8518e7&response_type=token&redirect_uri=spotifyconnect-android-login%3A%2F%2Fcallback&show_dialog=false&utm_source=spotify-sdk&utm_medium=android-sdk&utm_campaign=android-sdk&scope=user-read-private%20streaming
04-06 17:13:33.536 10990-10990/com.briantheastronaut.spotifyconnect D/SpotifyAuthHandler: start
04-06 17:13:34.748 10990-10990/com.briantheastronaut.spotifyconnect D/com.spotify.sdk.android.authentication.LoginActivity: Response: token
04-06 17:13:34.749 10990-10990/com.briantheastronaut.spotifyconnect D/SpotifyAuthHandler: stop
04-06 17:13:34.886 10990-10990/com.briantheastronaut.spotifyconnect W/InputMethodManager: Ignoring onBind: cur seq=169, given seq=168
04-06 17:13:36.165 10990-10990/com.briantheastronaut.spotifyconnect W/linker: /data/app/com.briantheastronaut.spotifyconnect-2/lib/arm/libspotify_embedded_shared.so: unused DT entry: type 0xf arg 0xc77
04-06 17:13:36.964 10990-11118/com.briantheastronaut.spotifyconnect E/SpotifySDKNative: Unknown connection error of type '5' received
04-06 17:13:36.974 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: User logged in
04-06 17:13:36.989 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackNotifyBecameActive
04-06 17:13:37.172 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackNotifyMetadataChanged
04-06 17:13:37.173 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackNotifyMetadataChanged
04-06 17:13:37.173 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackNotifyContextChanged
04-06 17:13:37.621 10990-11118/com.briantheastronaut.spotifyconnect D/AudioTrack: Client defaulted notificationFrames to 2362 for frameCount 7088
04-06 17:13:37.655 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackNotifyTrackChanged
04-06 17:13:37.656 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackEventAudioFlush
04-06 17:13:37.657 10990-10990/com.briantheastronaut.spotifyconnect D/MainActivity: Playback event received: kSpPlaybackNotifyPlay

**Comment by jnasti1** [comment]
I had this problem when I downloaded the spotify-auth lib but it was missing the .aar file that the tutorial pointed out. I opened the spotify-auth project in Android Studio, built it and then copied the .aar build output to this tutorial libs directory as it said.

Instead, only manually copy the spotify-player .aar to app/libs and add these two lines under app module build.gradle's dependencies section:

    // This library handles authentication and authorization
    compile 'com.spotify.android:auth:1.0.0-alpha'

    // This library handles music playback, uses local app/libs copy
    compile 'com.spotify.sdk:spotify-player-24-noconnect-2.20b@aar'

**Comment by zerochl** [comment]
delete testCoverageEnabled true
