### ISSUE TITLE
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=yourcustomprotocol://callback

### ISSUE THREAD

**Issue by chukzzy** [spotify/android-sdk#367]
239 9711-9711/com.moodsync.moodsync.moodsync W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=moodsync://returnAfterLogin/ }
06-10 06:34:54.239 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4224)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4183)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.Activity.startActivity(Activity.java:4507)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.Activity.startActivity(Activity.java:4475)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at com.spotify.sdk.android.authentication.LoginDialog$2.shouldOverrideUrlLoading(LoginDialog.java:165)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
06-10 06:34:54.240 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:339)
06-10 06:34:54.241 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
06-10 06:34:54.241 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:256)
06-10 06:34:54.241 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-10 06:34:54.241 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
06-10 06:34:54.241 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-10 06:34:54.241 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.os.Looper.loop(Looper.java:154)
06-10 06:34:54.242 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
06-10 06:34:54.242 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-10 06:34:54.242 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-10 06:34:54.243 9711-9711/com.moodsync.moodsync.moodsync W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by kevinkokomani** [comment]
Have you added:

<activity
            android:name="com.spotify.sdk.android.authentication.LoginActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"/>

to your AndroidManifest file?

**Comment by sannysanoff** [comment]
In the spotify android example, AndroidManifest.xml contains invalid reference to com.spotify.sdk.android.authentication.WebAuthResultActivity which is supposed to be activated by <data android:host="callback" android:scheme="myscheme"/>

The class WebAuthResultActivity itself is not in SDK, so it's time to clarify stuff somehow.

Thanks.

**Comment by Coding-Hen** [comment]
I agree with this it would be nice to know why there are these references if they dont work, i am also having the same issue. Can we have a Dev give us an update please! :)
